# SECTION 1
SUPER_ADMIN_NAME = 'super_admin'
SUPERINTENDENT_NAME = 'superintendent'
SUPER_AREA_ADMIN_NAME = 'super_area_admin'
SUPER_DISTRICT_ADMIN_NAME = 'super_district_admin'
SUPER_ASSEMBLY_ADMIN_NAME = 'super_assembly_admin'
AREA_ADMIN_NAME = 'area_admin'
DISTRICT_ADMIN_NAME = 'district_admin'
ASSEMBLY_ADMIN_NAME = 'assembly_admin'
ASSISTANCE_ADMIN_NAME = 'assistance_admin'

# SECTION 2
SUPER_ADMIN = ((SUPER_ADMIN_NAME, 'Super Admin'),)
SUPERINTENDENT = ((SUPERINTENDENT_NAME, 'Superintendent'),)
SUPER_AREA_ADMIN = ((SUPER_AREA_ADMIN_NAME, 'Super Area Admin'),)
SUPER_DISTRICT_ADMIN = ((SUPER_DISTRICT_ADMIN_NAME, 'Super District Admin'),)
SUPER_ASSEMBLY_ADMIN = ((SUPER_ASSEMBLY_ADMIN_NAME, 'Super Assembly Admin'),)
AREA_ADMIN = ((AREA_ADMIN_NAME, 'Area Admin'),)
DISTRICT_ADMIN = ((DISTRICT_ADMIN_NAME, 'District Admin'),)
ASSEMBLY_ADMIN = ((ASSEMBLY_ADMIN_NAME, 'Assembly Admin'),)
ASSISTANCE_ADMIN = ((ASSISTANCE_ADMIN_NAME, 'Assistance Admin'),)


# SECTION 3
USER_PERMS_NAMES = [
    SUPER_ADMIN_NAME, SUPERINTENDENT_NAME, SUPER_AREA_ADMIN_NAME, SUPER_DISTRICT_ADMIN_NAME,
    SUPER_ASSEMBLY_ADMIN_NAME, AREA_ADMIN_NAME, DISTRICT_ADMIN_NAME, ASSEMBLY_ADMIN_NAME, ASSISTANCE_ADMIN_NAME
]

# SECTION 4
PERMS_CONSTANT_LIST = [
    SUPER_ADMIN, SUPERINTENDENT, SUPER_AREA_ADMIN, SUPER_DISTRICT_ADMIN, SUPER_ASSEMBLY_ADMIN,
    AREA_ADMIN, DISTRICT_ADMIN, ASSEMBLY_ADMIN, ASSISTANCE_ADMIN
]
